### ISSUE TITLE
Prebuilt binaries release does not work on iOS

### ISSUE THREAD

**Issue by ChristianMcFarlaneWork** [khindemit/unity-project-vorbis#2]
Hey @khindemit,
Thanks so much for this plugin, It's been a massive help with what we've been working on.
The latest libraries [(0.1.1)](https://github.com/khindemit/unity-vorbis/releases/tag/0.1.1) release for android are working perfectly, no issues with symbols missing or audio speedup on export!
However we've just made a build for iOS and it has the same problem that the old 0.1.0 release binaries are having. Inspecting the symbols for the corresponding .dylib shows that they have a different exported name, and contain the audio speedup issues that the android symbols was also having.
libVorbisPlugin.dylib symbols:
```
...
000000000000170c T _DecodePcmDataFromFile
0000000000001a5a T _EncodePcmDataToFile
0000000000001a1e T _FreeSamplesArrayNativeMemory
0000000000014846 T __book_maptype1_quantvals
...
```
We're making a new build for iOS now and will get back to you when it's built and if it works. 
Cheers, and thankyou again for the plugin!
Chris.

**Comment by gindemit** [comment]
Hey Chris,
thanks for trying the plugin out. I'll have a look at the iOS libraries in the next couple of days.

**Comment by gindemit** [comment]
Hey Chris,

sorry for the long delay. There was an issue on iOS with integer types on C. The long on iOS is 8 bytes long, but C# expects that the parameters are 4 bytes big. I fixed the issue and rebuild the libraries for Windows, Android, Mac OSX and iOS.

Please test the release out: https://github.com/khindemit/unity-wrapper-vorbis/releases/tag/0.1.2

If you encounter any issues, please report it to me.
Have a nice day!

**Comment by gindemit** [comment]
Since there is no answer for a long time, I close this issue. If you encounter any issues with the plugin, please create a new issue here.
