### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AdamFrisby** [khindemit/unity-project-vorbis#3]
Hi there! Could I ask what License this project is under? (also this one: https://github.com/khindemit/unity-wrapper-vorbis ) thankyou!

**Comment by gindemit** [comment]
Hello, MIT.
Are you missing some features?

**Comment by AdamFrisby** [comment]
No that's it - thank you! Just was a missing License file in the project directory and had to tick a few paperwork documents, thankyou for making the library! :)
